### ISSUE TITLE
Consider radio power state?

### ISSUE THREAD

**Issue by triblondon** [WICG/priority-hints#30]
For battery powered devices, it seems reasonable to me to use importance as an indication of whether a fetch can be deferred until a radio power up is required by some other, higher priority fetch.  Would you consider indicating in the spec here that, as a general principle, importance may be used by UAs to affect not just the order of fetches.  In https://github.com/WICG/priority-hints/issues/23, there's a use case for triggering a resource to load on an event that's not expected to occur for some time.  This is potentially a similar situation.

**Comment by igrigorik** [comment]
FWIW, I've tried to push this particular rock (accounting for radio state) up this hill for a while. Unfortunately, in practice, getting this information reliably from the device net-stack, across all the different platforms, is a tall order. Also, in practice, simple heuristics like coalescing requests would get you most of the way there, see https://github.com/whatwg/fetch/issues/184 < we should tackle that, I think that's the right place to solve this.

**Comment by domfarolino** [comment]
Definitely agree that letting "importance" have an effect on things other than priority (please see first para under https://wicg.github.io/priority-hints/#use-cases) is important, however I agree that the particular concern brought up in this issue is best driven by the Fetch issue that Ilya points to; closing this for now, though it would be great to see more people chime in on the aforementioned issue!
