### ISSUE TITLE
Struggling to get Priority Hints to work on a preloaded image

### ISSUE THREAD

**Issue by smashingstuff** [WICG/priority-hints#63]
I appreciate that importance is just a hint. That said, I'm struggling to see why the following code, within `<head>`, is not making any difference to the loading priority in Chrome 98. In Network Tools the priority remains stubbornly "Low".

`<link rel="preload" as="image" href="https://turbo.freevideogamesonline.org/core-images/preloaders/jetpac-loader.gif" importance="high" />`

The image is implemented on the page as...

`<div id="game-container" style="background-image: url('https://turbo.freevideogamesonline.org/core-images/preloaders/jetpac-loader.gif'); background-repeat: no-repeat; background-position: center;"></div>`

What are we doing wrong?

The site can be tested at https://freejetpac.org, but in case we implement any changes or workarounds before this message gets read, please use the following archive link:

https://freejetpac.org/index-priority-hints.php

Thanks in advance

**Comment by pmeenan** [comment]
Do you have an [origin trial token](https://developer.chrome.com/origintrials/#/register_trial/365917469723852801) registered and sent? I don't see one in the response headers for the HTML (or in markup but it needs to be in the headers to work).

It's still behind origin trial in Chrome and needs to be opted-in with a token.

Once it ships (hopefully really soon now) it won't need the token but the attribute name will likely be changing to ```fetchPriority=high``` instead of ```importance```

**Comment by pmeenan** [comment]
FWIW, this repo is for the spec itself. If you have a Chrome-specific issue I recommend opening a [bug](https://new.crbug.com).
