### ISSUE TITLE
fetchpriority IDL attribute should be fetchPriority

### ISSUE THREAD

**Issue by domenic** [WICG/priority-hints#68]
See [W3C TAG Design Principles](https://w3ctag.github.io/design-principles/#:~:text=Note%20that%20in%20particular%2C%20when%20a%20HTML%20attribute%20is%20reflected%20as%20a%20property%2C%20the%20attribute%20and%20property%E2%80%99s%20casings%20won%E2%80%99t%20necessarily%20match)

**Comment by pmeenan** [comment]
@domenic which IDL in particular should be camel-cased?

`HTML elements and attributes` are to be `Lowercase, concatenated` according to the table (and matches the other attributes like crossorigin).  Is it since it's a property rather than an attribute?

I originally had it camel-cased but none of the other attributes in the HTML spec on the same DOM elements were camel.

**Comment by domenic** [comment]
The HTML attribute (i.e. content attribute) should be fetchpriority (all lowercase, concatenated). The IDL attribute (i.e. JavaScript property) should be fetchPriority (camel cased). The fetchPriority IDL attribute should reflect the fetchpriority content attribute.
