### ISSUE TITLE
Ok to archive?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/priority-hints#77]
Given what the spec says:
>  This specification is no longer relevant and has been merged directly into the [[FETCH|Fetch]] and [[HTML|HTML]] specifications.

is it ok to archive this repo and label it as a successful incubation?

**Comment by pmeenan** [comment]
@marcoscaceres  What happens when it is archived?

My main concern is for any inbound links to the spec that already exist on the web.  Currently they get redirected to the explainer that links them out to the HTML and Fetch specs for the details.  

When it is archived, will that still happen and it's more of a status/tracking thing or will the links break?

If it's just making it inactive but keeps the explainer and redirect in place then I'm fully supportive of archiving it.

**Comment by yoavweiss** [comment]
The links should still work fine. It would be impossible for folks to file new issues/PRs, but that's fine as they should file those against HTML and Fetch anyway.

**Comment by yoavweiss** [comment]
@pmeenan - friendly ping. Are you cool with archiving?

**Comment by pmeenan** [comment]
Yes, sorry - thought I responded here but I guess not.  Is there a process to mark the incubation as successful and switch the repository into archive mode?

**Comment by yoavweiss** [comment]
@marcoscaceres Did we settle on a label we want to apply for things that have graduated?

**Comment by marcoscaceres** [comment]
I think "graduated" should be fine, and "shipping-NNNNN". 

> When it is archived, will that still happen and it's more of a status/tracking thing or will the links break?

The links will still work.

**Comment by yoavweiss** [comment]
Added to that to topics.. Archiving!
